### ISSUE TITLE
`/example`?

### ISSUE THREAD

**Issue by corysimmons** [mighdoll/undo-peasy#4]
It'd be great if there was a _reeeally_ bare bones example of this in action. I think you could just nest an `/example` dir and just `.npmignore` it.

**Comment by mighdoll** [comment]
Here's an [example](https://stackblitz.com/edit/react-ts-yrvut5?file=UndoRedoButtons.tsx).

There are 3 or 4 lines you need to add to an easy-peasy app to support undo/redo, I tried to put a comment for each of the necessary changes.

Let me know if that helps.

**Comment by corysimmons** [comment]
That's awesome! Thank you.

I'm not sure I understand the other actions like group and such. I would love to be able to undo/redo specific branches on my global state tree. Are there much docs on that?

**Comment by mighdoll** [comment]
To undo/redo specific branches of your state tree, I'd suggest you try `noSaveKeys` to filter out the sections of the tree you don't want to save. 

You can also filter by action if you'd prefer. See `skipAction`. File an issue if those don't work for you. 

There is a hook for undo grouping. You might group if your code makes multiple state changes in response to one user action. That way pressing the undo button will undo all of the changes at once. 

If you find you're tempted to group things, first consider whether you might change your code so that one combined action does all of the changes. If that doesn't work, then consider using the undo grouping hook. If neither of those options work, consider using undo ignore, or the lower level actions to start and stop groups.

**Comment by corysimmons** [comment]
That's awesome thank you so much for your help and the great library!
